name: 'Cherry pick to branch on PR'
description:
    'Cherry-picks commits from a merged PR, creating a new PR to a target branch using a new temp pr branch'
author: 'voltterra'

branding:
    icon: 'copy'
    color: 'green'

inputs:
    target-branch:
        description: 'Name of the branch that cherry-pick PRs should target'
        required: true
    pr-creator-token:
        description:
            'Personal Access Token used to create the PR. Uses default actions
            token by default.'
        required: false
        default: ${{ github.token }}
    submodules-target-branch:
        description: >
            (optional) target branch for submodules. If set, the action will try
            to fast-forward all submodules to the newest version possible of
            this specified branch.
        required: false
        default: ''
    pr-assignee:
        description:
            '(optional) User ID to be assigned to the created PR. Will use the
            assignee of the original PR by default'
        required: false
        default: ''
    pr-new-branch:
        description:
            '(optional) The branch name that will contain cherry-picked commits.
            Default is original branch name + "cherry-pick" suffix. When set,
            the pr-branch-suffix input is skipped'
        required: false
        default: ''
    pr-branch-suffix:
        description:
            '(optional) The suffix for pr-new-branch name or the merged branch name.
            Default is "-cherry-pick"'
        required: false
        default: '-cherry-pick'
    pr-labels:
        description:
            'Comma-separated list of labels to add to this PR. Empty by default'
        required: false
        default: ''
    pr-title-suffix:
        description:
            '(optional) suffix to be added to the title of the created PR.
            [Cherry-Pick] by default'
        required: false
        default: '[Cherry-Pick]'

outputs:
    pr-number:
        description: 'The number of the created PR'

runs:
    using: node20
    main: dist/index.js
